### PR TITLE
use IMAGE_VERSION_SUFFIX instead of DATETIME 

### PR DESCRIPTION
**Pull request by joergho**
Use variable IMAGE_VERSION_SUFFIX variable instead of DATETIME. Using
IMAGE_VERSION_SUFFIX allows easier and more direct changes. The
variable is available since Yocto 2.6 and it is used also for other
name variables, e.g. IMAGE_NAME. It is set to "-${DATETIME}" per
default, so the naming does not change as long as IMAGE_VERSION_SUFFIX
is not overridden.

For more details, see:
https://www.yoctoproject.org/docs/latest/ref-manual/ref-manual.html#migration-2.6-image-kernel-artifact-naming-changes

### CODE REVIEW

**Comment by joergho** [comment]
I can also squash the 3 commits together if you'd prefer that.

**Comment by ckalluri73** [comment]
Could you please rebase the commits against the current master ? I will merge them in.

**Comment by mhatle** [comment]
Thanks for this comments.  These are indeed bugs in the current integration.  We'd like to get them resolved in master in the near future.

**Comment by ckalluri73** [comment]
I rebased and applied the patches on master. Closing this pull request.

**Pull request closed without merging**
