### PR TITLE
meta-xilinx-bsp depends on meta-xilinx-tools. Update layer.conf.

### PR DESCRIPTION
**Pull request by balister**
Signed-off-by: Philip Balister <philip@opensdr.com>

### CODE REVIEW

**Comment by ckalluri73** [comment]
The meta-xilinx layer doesnt have a dependency on meta-xilinx-tools while the other way round is true. This is intentional. The user can build images using just meta-xilinx layer. 
Is there anything specific you are trying to add the dependency ?

**Comment by mhatle** [comment]
It looks like there is a bug, u-boot has a dependency on a class that is only in meta-xilinx-tools.  This appears to be where the dependency is coming from.

**Comment by balister** [comment]
Any suggestions on how to fix this?

**Comment by mhatle** [comment]
In the very near future, I'm going to be going through the meta-xilimx, and all of the sublayers trying to better organize things.

I don't yet know how we're going to resolve this, but I suspect we'll be moving things that refer to xsct somewhere else (possibly meta-xilinx-tools?), items referring to the embeddedsw (not yet released) into their own work-in-progress layer, and focus the main meta-xilinux-bsp on enabling the SPL workflow, as well as the bootbin workflow (when meta-xilinx-tools is available).

**Comment by mhatle** [comment]
Progress report, we're likely going to be moving this recipe into meta-xilinx-tools.  We don't want to have meta-xilinx-bsp dependent on meta-xilinx-tools, even has an optional dependency.

**Comment by mhatle** [comment]
This never got closed out, it was resolved:

commit 11ed88c005173e357f6fc0eed520069de5b474e8
Author: Mark Hatle <mhatle@xilinx.com>
Date:   Wed Jun 8 17:41:33 2022 -0700

    uboot-device-tree: Move bbappend into meta-xilinx-tools
    
    The provencore bbappend only applied when meta-xilinx-tools is available, so
    move the bbappend to meta-xilinux-tools.
    
    Signed-off-by: Mark Hatle <mhatle@xilinx.com>
    (cherry picked from commit d44ab8d60eda1ba361715ad7dc8976dccf072e86)
    Signed-off-by: Mark Hatle <mhatle@xilinx.com>

**Pull request closed without merging**
