### PR TITLE
picozed-zynq7.conf: fix typo

### PR DESCRIPTION
**Pull request by njpillitteri**

### CODE REVIEW

**Comment by njpillitteri** [comment]
typo

**Comment by mharth** [comment]
can you provide your name and email address for Signed-off-by line ? I will create the patch and merge to master and sumo release. We usually dont do pull request, but use mailing list

**Comment by njpillitteri** [comment]
Nicholas Pillitteri
njpillitteri@gmail.com

I don't care about credit just please fix it.

**Comment by mharth** [comment]
its updated, thanks for the patch

**Pull request closed without merging**
