### PR TITLE
Update README.building.md

### PR DESCRIPTION
**Pull request by jwillemsen**
Correct link to Quick Start guide

### CODE REVIEW

**Comment by grsandeep85** [comment]
Thanks for submitting the patch. We will merge the changes.

**Comment by jwillemsen** [comment]
Maybe check all documentation links to yocto? For example https://github.com/Xilinx/meta-xilinx/blob/master/README.booting.md#preparing-sdmmc has also a broken link. 

Not sure whether there is a github action CI which automatically creates an issue when it detects a broken lnk

**Comment by jwillemsen** [comment]
There is, see https://github.com/technote-space/broken-link-checker-action

**Comment by jwillemsen** [comment]
Maybe https://github.com/lycheeverse/lychee-action can help here, run a github action on a schedule to check for broken links

**Comment by grsandeep85** [comment]
As part of patch https://github.com/Xilinx/meta-xilinx/commit/f1b4eae7dbd4af95c98329858aba8a7d14051262 this is fixed.

**Pull request closed without merging**
