### PR TITLE
Fix HDF_MACHINE issue

### PR DESCRIPTION
**Pull request by Livius90**
It's not good to hard assign HDF_MACHINE to a specific Xilinx development board in generic confs. This will cause a build error for other boards. Let it be assigned by MACHINE name in [external-hdf.bb from meta-xilinx-tools](https://github.com/Xilinx/meta-xilinx-tools/blob/rel-v2022.1/recipes-bsp/hdf/external-hdf.bb#L39).

### CODE REVIEW

**Comment by mhatle** [comment]
You need to override the HDF_MACHINE value in your own machine configuration.  This in intentionally set this way, as these HDF files enable qemu based environments (which is what the generics support)

See: https://github.com/Xilinx/meta-xilinx/blob/master/meta-xilinx-core/conf/machine/README

But the TLDR is you need to create your own machine.conf file for your own board.  At a MINIMUM the machine.conf should look like (assuming my-example.conf):

#### Preamble
MACHINEOVERRIDES =. "${@['', 'my-example:']['my-example' != '${MACHINE}']}"
#### Regular settings follow

require conf/machine/zynqmp-generic.conf

SOC_VARIANT = "ev"
HDF_MACHINE = "my-ev-board"

#### No additional settings should be after the Postamble
#### Postamble
PACKAGE_EXTRA_ARCHS:append = "${@['', ' my_example']['my-example' != "${MACHINE}"]}"

**Comment by Livius90** [comment]
I think, current HDF_MACHINE architect is not correct, i got many issue, when a try to use/build it for other board.

In generic config, it is not asigned by ??= or ?=, it means any other board like zc706-zynq7 will not work well, FSBL and bitstream can be incompatible in image booting. My opinian, HDF_MACHINE must be asigned outside from generic config somewhere. Now, only forcevariable overriding can help, but it is a really not nice, it is an ugly solution. If you would like to provide any qemu conf, the better to make a general qemu specific machine.conf and it is done.

Did you try to build and use any other boards than zc702-zynq7?

**Comment by Livius90** [comment]
I tried to build and use zcu104-zynqmp machine but it is using HDF_MACHINE = "zcu102-zynqmp" from zynqmp-generic.conf. It is not correct for ZCU104 dev board, totally. FSBL will be incorrect in booting, sure. I needed to remove HDF_MACHINE assigning in zynqmp-generic.conf and let it be assigned to MACHINE name in external-hdf.bb automatically.

**Comment by Livius90** [comment]
@mhatle 

Hi,
In latest rel-2022.2 i still have some issue in my custom machine conf, please see and review my new pull request.
https://github.com/Xilinx/meta-xilinx/pull/46
To use nicely your suggestion with `HDF_MACHINE = "my-ev-board"` in my-example.conf machine file, HDF_MACHINE must be assigned in weak mode in generic conf files before.

**Pull request closed without merging**
