### PR TITLE
Add support for Z-Turn board

### PR DESCRIPTION
**Pull request by OYTIS**
I'm working against rocko branch, so the PR is for Rocko, if you find it useful, I can test master and pyro.

ps7_init_gpl.* are generated by Vivado, dtb is borrowed from https://github.com/andreamerello/linux-zynq-stable

### CODE REVIEW

**Comment by OYTIS** [comment]
Ah, mailing list, OK.

**Comment by kenzhang82** [comment]
Any update in this PR? Has it been integrated into sumo and master?

**Comment by mharth** [comment]
Please push the kernel patch to mainline. Send the rest of the patch to meta-xilinx mailing list

**Comment by kenzhang82** [comment]
Thanks @mharth, I am asking because it has seen this patch being submitted to the mailing list (see here: https://lists.yoctoproject.org/pipermail/meta-xilinx/2018-March/003690.html), but not sure what the current status is. Are these changes being upstream, ie. merged to master or sumo branch?

**Pull request closed without merging**
