### PR TITLE
Add FPGA bitfile download support in the u-boot.scr.

### PR DESCRIPTION
**Pull request by adrianf0**
It is inspired on u-boot-zynq-uenv.bb

Signed-off-by: Adrian Fiergolski <adrian.fiergolski@fastree3d.com>

### CODE REVIEW

**Comment by ckalluri73** [comment]
Hi Adrian, can you please rebase the patch against the current master so that I can merge it in.

**Comment by adrianf0** [comment]
Hi Sai, done. Though I haven't tested this merge

**Comment by ckalluri73** [comment]
okay let me know once its tested and ready to merge.

**Comment by adrianf0** [comment]
I am running this patch on Zynqmp and it works properly.

**Comment by ckalluri73** [comment]
Rebased and applied to master. Closing this pull request. Thank you for the patches.

**Pull request closed without merging**
